### ISSUE TITLE
Reproducibility of Microsoft CLAP

### ISSUE THREAD

**Issue by Ming-er** [zhepeiw/clap_curation#1]
Dear author, sorry to bother you. During testing the zero-shot classification performance of urbansound8k with the Microsoft clap model, I got a 76% accuracy which is much higher than the original paper. I wonder if you have the same question. If so, the result of this work might seem less promising.

**Comment by zhepeiw** [comment]
> Dear author, sorry to bother you. During testing the zero-shot classification performance of urbansound8k with the Microsoft clap model, I got a 76% accuracy which is much higher than the original paper. I wonder if you have the same question. If so, the result of this work might seem less promising.

Thank you for your interest in our work! We'd like to confirm that, if loading Microsoft's pretrained checkpoint and following our inference script, we obtain a higher accuracy on Urbansound8K than what the original paper has reported (~77% vs ~74%), whereas on ESC (~83% vs ~83%) and TUT (~30% vs ~30%) our script is able to match the reported results closely. Our reproduction of the zero-shot evaluation is based on Microsoft's released code on ESC, and we did our best to reproduce results for other datasets despite the lack of details for data preprocessing for these datasets from their released code.

Additionally, we would like to mention that our training condition is different from the original CLAP, which could partially explain the performance discrepancy between our teacher model and Microsoft's model. In our experiments, the training of our student and teacher models are subject to the same training condition (which is different from Microsoft's CLAP); this performance gain suggests the effectiveness of our proposed approach.

**Comment by Ming-er** [comment]
Got it. Thanks for your reply.
